src/Entity/Module.php
<?php

namespace App\Entity;

use App\Repository\ModuleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ModuleRepository::class)
 */
class Module
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    // /**
    //  * @ORM\Column(type="integer", nullable=true)
    //  */
    // private $number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;


    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $temperature;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $duree_fonctionnement;

    // /**
    //  * @ORM\Column(type="float", nullable=true)
    //  */
    // private $donnees_envoyees;

    /**
     * @ORM\Column(type="integer")
     */
    private $etat_de_marche;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=ModuleCategory::class, inversedBy="modules")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    // public function getNumber(): ?int
    // {
    //     return $this->number;
    // }

    // public function setNumber(?int $number): self
    // {
    //     $this->number = $number;

    //     return $this;
    // }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getTemperature(): ?float
    {
        return $this->temperature;
    }

    public function setTemperature(?float $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getDureeFonctionnement(): ?float
    {
        return $this->duree_fonctionnement;
    }

    public function setDureeFonctionnement(?float $duree_fonctionnement): self
    {
        $this->duree_fonctionnement = $duree_fonctionnement;

        return $this;
    }

    // public function getDonneesEnvoyees(): ?float
    // {
    //     return $this->donnees_envoyees;
    // }

    // public function setDonneesEnvoyees(?float $donnees_envoyees): self
    // {
    //     $this->donnees_envoyees = $donnees_envoyees;

    //     return $this;
    // }

    public function getEtatDeMarche(): ?int
    {
        return $this->etat_de_marche;
    }

    public function setEtatDeMarche(int $etat_de_marche): self
    {
        $this->etat_de_marche = $etat_de_marche;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?ModuleCategory
    {
        return $this->Category;
    }

    public function setCategory(?ModuleCategory $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    

}

src/Controller/ModulesController.php
<?php

namespace App\Controller;

use App\Entity\Historique;
use App\Entity\Module;
use App\Repository\ModuleCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ModulesController extends AbstractController
{
    /**
     * @Route("/modules", name="modules")
     */

    public function index(ModuleCategoryRepository $moduleCategoryRepository, Request $request): Response
    {


        //la on appelle la table Module
        $repository = $this->getDoctrine()->getRepository(Module::class);
        //Affiche tout les modules disponible
        $Modules = $repository->findAll();

        //Affiche du menu de catégorie
        $category = $moduleCategoryRepository->findAll();


        return $this->render('modules/index.html.twig', [
            'modules' => $Modules,
            'categories' => $category

        ]);
    }


    /**
     * @Route("/module/fonctionne/{id}", name="marche")
     */
    public function EtatMarche($id, Module $Module, Request $request): Response
    {

        //-------------------------------------------------------
        $entityManager = $this->getDoctrine()->getManager();
        $repository = $entityManager->getRepository(Module::class)->find($id);
        $repository->setEtatDeMarche("1");
        //dump($repository);
        //-------------------------------------------------------
        $Commentaire = $entityManager->getRepository(Module::class)->find($id);
        $idModuleCommentaire = $Commentaire->getId();
        $NameModuleCommentaire = $Commentaire->getName();

        $commentaire = new Historique();
        $commentaire->setCommentaire(" 🟢 Le module n° $idModuleCommentaire : $NameModuleCommentaire fonctionne correctement ");
        $entityManager->persist($commentaire);

        //-------------------------------------------------------

        $entityManager->flush();

        $this->addFlash('success', 'Votre module fonctionne');
        
        $CurrentPage = $request->headers->get('referer');
        return $this->redirect($CurrentPage);
        // return $this->redirecttoRoute('modules');

    }


    /**
     * @Route("/module/arret/{id}", name="arret")
     */
    public function EtatArret($id, Module $Module, Request $request): Response
    {

        $entityManager = $this->getDoctrine()->getManager();
        $repository = $entityManager->getRepository(Module::class)->find($id);
        $repository->setEtatDeMarche("0");

        //-------------------------------------------------------
        $Commentaire = $entityManager->getRepository(Module::class)->find($id);
        $idModuleCommentaire = $Commentaire->getId();
        $NameModuleCommentaire = $Commentaire->getName();

        $commentaire = new Historique();
        $commentaire->setCommentaire(" 🔴 Attention ! Le module n° $idModuleCommentaire : $NameModuleCommentaire s'est arrêté ! ");
        $entityManager->persist($commentaire);

        //-------------------------------------------------------


        $entityManager->flush();

      
        $this->addFlash('danger', 'Votre module a bien été arrêté');
        $CurrentPage = $request->headers->get('referer');
        return $this->redirect($CurrentPage);

    }






    /**
     * @Route("/module/disfonction/{id}", name="disfonction")
     */
    public function EtatDisfonction($id, Module $Module, Request $request): Response
    {

        $entityManager = $this->getDoctrine()->getManager();
        $repository = $entityManager->getRepository(Module::class)->find($id);
        $repository->setEtatDeMarche("2");


        //-------------------------------------------------------
        $Commentaire = $entityManager->getRepository(Module::class)->find($id);
        $idModuleCommentaire = $Commentaire->getId();
        $NameModuleCommentaire = $Commentaire->getName();


        $commentaire = new Historique();
        $commentaire->setCommentaire(" ⚠️ Le module n° $idModuleCommentaire : $NameModuleCommentaire est dans un état de disfonctionnement");
        $entityManager->persist($commentaire);

        //-------------------------------------------------------

        $entityManager->flush();

        $this->addFlash('danger', 'Attention, votre module rencontre un disfonctionnement');

        $CurrentPage = $request->headers->get('referer');
        return $this->redirect($CurrentPage);
    }
}

templates/modules/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vos Modules{% endblock %}

{% block body %}

<div class="homeCover">
    <h1 class="col-lg-8">Vos modules : </h1>
    <p class="m-5">Depuis plusieurs années, les objets connectés à internet se multiplient, c'est pourquoi nous proposons des solutions efficaces afin que vous puissiez gérer et visualiser au mieux vos modules.</p>
</div>


        <div class="MenuCategory">
             {% for category in categories %}  
                <div class="m-2">
                    <a class="btn btn-primary" href="{{ path('category', {'id':category.id}) }}">{{ category.CategoryName }}</a>
                </div>
             {% endfor %}
        </div> 


    <div class="AllModule ">

        {% for module in modules %}
            <div class="card cardModule col-lg-2" >
    
                {% if module.etatDeMarche == 1 %}
                    <div class="etattitle">
                        <li class=" etat">
                            <div class="circleGreen"></div>
                            <div class="circleVoid"></div>
                            <div class="circleVoid"></div>
                        </li>
                        <h6 class="card-title">Module n°{{ module.id}}</h6>
                    </div>
                {% endif %}
                {% if  module.etatDeMarche == 0 %}
                    <div class="etattitle">
                        <li class=" etat">
                            <div class="circleVoid"></div>
                            <div class="circleVoid"></div>
                            <div class="circleRed"></div>
                        </li>
                        <h6 class="card-title">Module n°{{ module.id}}</h6>
                    </div>
                {% endif %}
                {% if module.etatDeMarche == 2 %} 
                    <div class="etattitle">
                        <li class=" etat">
                            <div class="circleVoid"></div>
                            <div class="circleOrange"></div>
                            <div class="circleVoid"></div>
                        </li>
                        <h6 class="card-title">Module n°{{ module.id}}</h6>
                    </div> 
                {% endif %}

                <img class="imgModule" src="{{asset('img/module/' ~ module.image)}}" class="" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{module.name}}</h5>
                    <p class="card-text">Type : {{module.category.CategoryName}}</p>
                    <p class="card-text">{{module.description}}</p>

                    <div class="divButtonCard">
                        <a href="{{path('edit', {id: module.id})}}" class="btn btn-primary">Modifier</a>
                        <a href="{{path('delete', {id: module.id})}}" class="btn btn-primary">Supprimer</a>
                    
                        {% if module.etatDeMarche == 1 %}
                                <a href="{{path('arret', {id: module.id})}}" class="btn btn-primary">Arret</a>
                                <a href="{{path('disfonction', {id: module.id})}}" class="btn btn-primary">Disfonction</a>
                        {% endif %}
                        {% if module.etatDeMarche == 0 %}
                                <a href="{{path('marche', {id: module.id})}}" class="btn btn-primary">Marche</a>
                                <a href="{{path('disfonction', {id: module.id})}}" class="btn btn-primary">Disfonction</a>

                        {% endif %}
                        {% if module.etatDeMarche == 2 %}
                                <a href="{{path('marche', {id: module.id})}}" class="btn btn-primary">Marche</a>
                                <a href="{{path('arret', {id: module.id})}}" class="btn btn-primary">Arret</a>
                        {% endif %}
                        
                    </div>
                </div>

            </div>
        {% endfor %}
    </div>


{% endblock %}